### ISSUE TITLE
IO Safety violation runtime error in debug mode

### ISSUE THREAD

**Issue by un-lock-able** [stack-rs/rattan#80]
When running in debug mode, the binary cannot start correctly but instead throws out runtime error and terminates itself after creating the veth pair. However, if we swich to release mode, the binary can successfully start and behaves as expected.

Terminal log to reproduce:
```
unlockable@theresa:~/repos/rattan$ cargo run --release -- --uplink-delay 10ms
    Finished `release` profile [optimized + debuginfo] target(s) in 0.09s
     Running `sudo -E target/release/rattan --uplink-delay 10ms`
root@theresa:~/repos/rattan# ping 10.2.1.1 -c 3
PING 10.2.1.1 (10.2.1.1) 56(84) bytes of data.
64 bytes from 10.2.1.1: icmp_seq=1 ttl=64 time=10.3 ms
64 bytes from 10.2.1.1: icmp_seq=2 ttl=64 time=10.4 ms
64 bytes from 10.2.1.1: icmp_seq=3 ttl=64 time=10.7 ms

--- 10.2.1.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 10.259/10.444/10.689/0.180 ms
root@theresa:~/repos/rattan# exit
exit
unlockable@theresa:~/repos/rattan$ cargo run -- --uplink-delay 10ms
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
     Running `sudo -E target/debug/rattan --uplink-delay 10ms`
fatal runtime error: IO Safety violation: owned file descriptor already closed
Aborted
unlockable@theresa:~/repos/rattan$
```

**Comment by BobAnkh** [comment]
Provide some references to fix this issue:

- [alacritty/alacritty#7996](https://github.com/alacritty/alacritty/pull/7996)
- [zed-industries/zed#12114](https://github.com/zed-industries/zed/issues/12114)

**Comment by un-lock-able** [comment]
I dig down some more and I suspect that now there are multiple places involving `NetNS` are all causing the problem.

In `rattan-core/src/metal/veth.rs`, inside `VethPairBuilder::build_impl()`, adding a piece of code of 
```rust
let current_env = NetNS::current()?;
drop(current_env);
```
would immediately trigger this error message. I now suspect that the `NetNS::drop()` function does not handle the fd it owns gracefully and the fd could be closed multiple times.

Also, even if I avoid creating the "current ns" by simply replacing the[ `.unwrap_or(NetNS::current()?)`](https://github.com/stack-rs/rattan/blob/ce0384a1fee5f801d6e822af3f03a1854dc3ec7d/rattan-core/src/metal/veth.rs#L352) on lines 344 and 352 with a simple `expect()`, the same error message shows up again at the end of the for loop that starts from [line 358](https://github.com/stack-rs/rattan/blob/ce0384a1fee5f801d6e822af3f03a1854dc3ec7d/rattan-core/src/metal/veth.rs#L358), right after the code exits the "for namespace". I'm still trying to figure out what is dropped when the for loop ended and which caused this problem.

**Comment by BobAnkh** [comment]
Reference for the double close:

- [DefaultEnv::umount_ns](https://github.com/stack-rs/rattan/blob/ce0384a1fee5f801d6e822af3f03a1854dc3ec7d/rattan-core/src/metal/netns.rs#L55) called by [DefaultEnv::remove](https://github.com/stack-rs/rattan/blob/ce0384a1fee5f801d6e822af3f03a1854dc3ec7d/rattan-core/src/metal/netns.rs#L182)
- [NetNs::drop](https://github.com/stack-rs/rattan/blob/ce0384a1fee5f801d6e822af3f03a1854dc3ec7d/rattan-core/src/metal/netns.rs#L309)
